namespace DivaniMods;

public enum DivaniRpcCalls : uint
{
    DoShuffle = 200,
    StealModifier = 201,
    GiveRandomModifier = 202,
    StartLockdown = 203,
    EndLockdown = 204,
    PlacePortal = 205,
    UsePortal = 206,
    ResetPortals = 207,
    PlagueDoctorSetInfected = 208,
    PlagueDoctorUpdateProgress = 209,
    PlagueDoctorTurnIntoAmnesiac = 210,
    PlaceBeacon = 211,
    FragPassBomb = 212,
    InnocentTaunt = 213,
    OpportunistWin = 214,
    RecruiterSetPendingTarget = 215,
    RecruitImpostorFollowUp = 216,
    DemolitionistPlantSabotage = 217,
    DemolitionistDefuseSabotage = 218,
    DemolitionistSabotageExpired = 219,
    DomesmithPlaceDome = 220,
    DomesmithRemoveDome = 221,
    DomesmithBlockedKill = 222,
    SummonerSetPendingTarget = 223,
    SummonerRecruitRevenant = 224,
    RevenantKill = 225,
    OpportunistWildcard = 226,
    OpportunistWildcardRefund = 227,
    SproutCollect = 228,
    MosquitoSpawn = 229,
    MosquitoSting = 230,
    MosquitoSwat = 231,
    ObfuscatorSetSwaps = 232,
    ObfuscatorConsumeCharge = 233,
    DuelistStartDuel = 234,
    FragStolenNotify = 235,
    ArmoredAttacked = 236,
    ClockstopperResetCooldowns = 237,
    RetributionistStartRevenge = 238,
    RetributionistRevenge = 239,
    RetributionistRevengeFailed = 240,
    UavCall = 241,
    UavEnd = 242,
    CupidSetMatchTarget = 243,
    CupidFinalizeLovers = 244,
    OpportunistVotesSync = 245,
}
